global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'jira'
    scheme: http
    metrics_path: '/plugins/servlet/prometheus/metrics?token=secrettoken'
    params:
        token: ['Urs7UCzuXn8Pz7kOVnvP59IBgVQeXYlAfBe']
    static_configs:
      - targets: ['jira:8080']

  - job_name: 'grafana'
    scheme: http
    metrics_path: '/metrics'
    static_configs:
      - targets: ['grafana:3000']